import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "mapbox-gl/dist/mapbox-gl.css";
import "next-cloudinary/dist/cld-video-player.css";
import "leaflet/dist/leaflet.css";
import "leaflet-routing-machine/dist/leaflet-routing-machine.css";

import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";

const geistSans = localFont({
  src: "../font/Geist-Regular.ttf",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../font/GeistMono-Regular.ttf",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "WCYDTT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
